### ISSUE TITLE
Device found but not recognized as Beacon

### ISSUE THREAD

**Issue by drstranges** [kontaktio/kontakt-android-sdk#118]
I'm  getting some strange logcat: D/kontakt.io SDK: Device found but not recognized as Beacon [name: Kontakt, address: XX:XX:XX:XX:XX:XX]. Howewer, beacons are discovered from time to time.

**Comment by michaldrabik** [comment]
@drstranges What is your SDK version?

**Comment by drstranges** [comment]
Kontakt SDK 3.1.0, Android 5.1

**Comment by michaldrabik** [comment]
@drstranges You probably don't need to worry about this. This is a general message that is thrown when scanned beacon frame is not consider "valid" for some reason (it can be due to malformed broadcast, or set up filtering). We should probably change text of this log to be less misleading.

Can you share your proximity manager configuration. Are you using regions or filters? Is this beacon an Eddystone or IBeacon (what is it's firmware)?

Regards

**Comment by drstranges** [comment]
Eddystone UID, URL, TLM, no shuffle, firmware 4.1
Gonfiguration:
- ScanMode.BALANCED;
- ScanPeriod.MONITORING;
- ActivityCheckConfiguration.DEFAULT;
- ForceScanConfiguration.MINIMAL;
- deviceUpdateCallbackInterval = TimeUnit.SECONDS.toMillis(5);
- RssiCalculators.DEFAULT;
- cacheFileName = "beacons";
- resolveShuffledInterval = 3;
- monitoringEnabled = true;
- monitoringSyncInterval = 60;
- eddystoneFrameTypes = Arrays.asList(EddystoneFrameType.URL);
- supportNonConnectableMode = true;

EddystoneNamespace.create("XY-Area", MY_BEACON_NAMESPACE, false)
EddystoneFilter: eDevice -> EVENTSSION_BEACON_NAMESPACE.equals(eDevice.getNamespace()))

**Comment by michaldrabik** [comment]
Ok so there's no need to worry. This message is displayed because you specified namespace filter and when bluetooth scanner detects other frames first (Eddystone URL or TLM) that don't contain namespace information it won't parse it. As I said We will refactor this log so it won't show up in cases like this.

Regards
