### ISSUE TITLE
Make source actually available

### ISSUE THREAD

**Issue by code-mc** [kontaktio/kontakt-android-sdk#119]
I'm trying to use this in Xamarin and the decompiled java code is full of bugs. If you could just upload the actual source to GitHub (why would you even put it on github if you're not going to make it available) that would be great and actually give me a chance at trying to port this over.

**Comment by stoprocent** [comment]
Hi @code-mc, Marek here. I am Mobile Lead at Kontakt.io. 

There are many reasons why our SDK is not open source (yet).
From licensing to many others I will not share right now. 

We are planning to port our SDK to platforms like React Native, Xamarin etc. and it would be great to get a support from the community but I would like to know a little more about people doing it.
I really appreciate your help but I can't just click and share the code because you want us to do it.

Answering your question ... There are many reasons why we are using github to host our SDK. 
We are using Github internally with private repos, our sample code is open sourced on Github and Issues are used to report bugs so I see no reason to move SDK part to a different place just because it is not open source. 

I'm happy to talk about supporting more platforms but we want to roll out both iOS and Android otherwise there is no reason to support such a platforms.

We can keep this issue open for now if you want to continue this discussion.

**Comment by code-mc** [comment]
Thanks for the reply. I understand, I was mostly just curious if releasing the source was an option or not.

**Comment by codercampos** [comment]
I hope you release your SDK for Xamarin because there are some people that actually wants to use your products on Xamarin. Watching this back in the future

**Comment by hernandoz** [comment]
Hi , are you planning to make this available for Xamarin forms ?
