### ISSUE TITLE
Android SDK Proguard Issue

### ISSUE THREAD

**Issue by abhirav** [kontaktio/kontakt-android-sdk#120]
Hi, 
I am using Kontakt SDK v3.0.0. It has proguard.txt file in aar file which has tag "-dontobfuscate". This is disallowing my app to obfuscate and not able to generate mapping.txt file. Could you provide solution how to avoid using Kontakt SDK proguard file?

**Comment by michaldrabik** [comment]
@abhirav Are you getting any errors or your project compiles and runs fine?

**Comment by abhirav** [comment]
Hi,
No there are no errors. There are two things happening. First because of -dontobfuscate, the code is easily readable by reverse engineering and Secondly, we are using maven plugin method, uploadArchives which throws error while publishing artefact, "Cannot publish artifact 'app.map (appmodule:app:unspecified)' (/opt/jenkins_dev/workspace/appmodule/app/build/outputs/mapping/release/mapping.txt). Because of "-dontobfuscate", mapping.txt is not generated.  If I remove Kontakt Library, mapping.txt do gets generated. I can install app in the mobile from Android studio, but our CI thorws above error while publishing.

**Comment by michaldrabik** [comment]
@abhirav Yes, the -dontobfuscate tag should clearly NOT be there. This is our fault it will be fixed in upcoming update. 

Meanwhile please give this 3.1.1 version a try. It is present on our Bintray repository. It contains no obfuscation tags + some bug fixes. 

To use it modify your app's module `build.gradle`:

```
android {
...
}

repositories {
  maven {
    url  "http://dl.bintray.com/kontaktio/maven"
  }
}

dependencies {
  // Other dependencies

  compile 'com.kontaktio:sdk:3.1.1-RC2'

  // Other dependencies
}
```

Let me know if that solves your proguard issue

**Comment by abhirav** [comment]
Hi @michaldrabik , it is working. Thanks.However I had to change my code little bit. Hope It doesn't have much impact.

Previous SDK version:

```
public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
                final UUID proximityUUID = iBeaconAdvertisingPacket.getProximityUUID();
```

New SDK version:

```
 public boolean apply(IBeaconDevice iBeaconDevice) {
                final UUID proximityUUID = iBeaconDevice.getProximityUUID();
                return proximityUUID.equals(KontaktSDK.DEFAULT_KONTAKT_BEACON_PROXIMITY_UUID);
```

**Comment by michaldrabik** [comment]
No it won't. 

Only thing you should revise is ProximityManager configuration. If you have set `activityCheckConfiguration` to `MINIMAL` you should change it to `ActivityCheckConfiguration.create(5000, 5000)` because in 3.1.x `MINIMAL` is 3000, 1000 ms. while in 3.0.0 it is 5000, 5000.

Also it is a good Java practice to compare constant String to variable so you don't get unexpected NPE:

```
public boolean apply(IBeaconDevice iBeaconDevice) {
                final UUID proximityUUID = iBeaconDevice.getProximityUUID();
                return KontaktSDK.DEFAULT_KONTAKT_BEACON_PROXIMITY_UUID.equals(proximityUUID);
```
