### ISSUE TITLE
Strange Behavior during iBeacon parameters editing

### ISSUE THREAD

**Issue by palettodiferro** [kontaktio/kontakt-android-sdk#121]
Hi,

I'm working with your beacons and I realized a strange behavior using your official Android App.
Beacons are detected perfectly also into my custom Android App, but when I try to edit Major and Minor parameter from your App, more times your App give me a Toast message error advicing me to restart Bluetooth and retry. After that, the same beacon becomes not detected for about 20 minuts for both App (my custom App and yours App). I'm using iBeacon protocol for all beacons.
Why that Behavior?

Thanks.

**Comment by michaldrabik** [comment]
Due to unstable Android bluetooth stack on some devices there is a chance that configuration will fail occasionally and Kontakt.io beacon will enter non-connectable mode for 20 minutes as a security measure. If this happens feel free to open your beacon take out battery and put it back in. This brings beacon back to its normal state.

By the way what version of Kontakt.io Android App do you have and what device are you using? 

Regards.

**Comment by palettodiferro** [comment]
I'm using your last version Android App and the smartphone I'm using is a Honor 7 device with Android 5.0.2 version.
