### ISSUE TITLE
Scanning beacon interval

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-android-sdk#128]
Hi,

I logged the callbacks for scanning events in my current setup and it seems that it takes around 30seconds before a beacon is discovered and/or updated. The only parameter that makes sense is the `ActivityCheckConfiguration` where I set it to 30 seconds. But according to the documents, the value here is just a reference to determine whether a beacon has been lost.

I would like to know how I can reduce the 30 seconds interval. Here's my configuration at the moment. 

``` java
mProximityManager.configuration()
                .scanMode(ScanMode.LOW_LATENCY)
                .scanPeriod(ScanPeriod.RANGING)
                .activityCheckConfiguration(new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(30), TimeUnit.SECONDS.toMillis(5)))
                .forceScanConfiguration(ForceScanConfiguration.MINIMAL)
                .deviceUpdateCallbackInterval((int) ScanContext.DEFAULT_DEVICES_UPDATE_CALLBACK_INTERVAL)
                .rssiCalculator(RssiCalculators.DEFAULT)
                .monitoringEnabled(true)
                .monitoringSyncInterval(10);
```

**EDIT**
If I use ActivityCheckConfiguration to MINIMAL, my beacons are lost every 5 seconds. This means we don't get an update from the Beacon until every 30 seconds. The current configuration of the beacon is set at:

TxPower: 2
Interval: 100 ms

Is TxPower related to how often the beacon is broadcasting? Also, an interval of 100 ms should be enough for us to get updates at least every minute or so, right?

**Comment by michaldrabik** [comment]
@jcyu0208 Your configuration looks just fine. ActivityCheckConfiguration (30,5) is OK. With this configuration the device should detect beacon within a second (if it is in range).

TxPower says how strong the beacon signal is, not how often it is broadcasted. TxPower 2 is pretty low which means the beacon will only be detectable within a short range. I think you can change those values to like:

TxPower: 4 or 3 (or even more - it depends on your usecase)
Interval: 250ms (this means the beacon will broadcast 4 times per second - it's more than enough)

Maybe your problems are caused by your device. What phone are you using?

You could always try installing [NRF CONNECT](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) app and see how does it handle your beacons.
