### ISSUE TITLE
What is the difference between onBeaconsDiscovered in ranging and onBeaconsUpdated in monitoring

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#16]
We are developing app using kontakt sdk for multiple beacons detection. We can connect to the beacons in two ways via  Monitoring and ranging.
We developed two POC's one related to monitoring and another one related to ranging.
We need to show distance from current device(mobile) to beacon while user moving inside the room.
From sdk we found that onBeaconsDiscovered  in ranging gives the detected beacons information i.e RSSI, TXPower etc. through List<BeaconDevice>. Similarly while monitoring  onBeaconsUpdated gives the list of detected beacons information.
Is any difference between these two? In our application we always require distance between mobile and beacons.

We observed that these events not firing after some time. But we need to update distance when user moves from one location to another location.

Please provide solution for us.

**Comment by dawidgdanski** [comment]
1. Is any difference between these two?
   Technically, there is no difference with these two types of scan. Ranging in Android SDK is considered as subset of Monitoring in terms of functionality but it employs a bit less resources in order to optimize battery power consumption. 
   onBeaconsDiscovered provides basically the same information as onBeaconsUpdated.

If the distance is the only thing that you require then I suggest choosing ranging.
1. We observed that these events not firing after some time.
   Could you be more specific? Could you provide any code or describe how BeaconManager's configuration part looks like?
