### ISSUE TITLE
Simulated iBeacon Not detected

### ISSUE THREAD

**Issue by verma171** [kontaktio/kontakt-android-sdk#174]
I am using your SDK android for beacon detection, I am simulating beacon from third party apps available on store, strange but you SDK not detecting simulated iBeacon  https://play.google.com/store/apps/details?id=net.alea.beaconsimulator

**Comment by sbobowiec** [comment]
The problem is with advertising packet transmitted by simulated iBeacon. It does not contain first 3 bytes, called standard BLE flags so manufacturer data starts from index number 2 instead of 5 - more details here: [iBeacon packet structure](https://en.wikipedia.org/wiki/IBeacon#Packet_Structure_Byte_Map).
This is the reason why iBeacon frame validation fails so you don't get any discovery callback.

**Comment by verma171** [comment]
Thanks for the quick response : 
I want to perform load testing of 100 beacons that why I need to simulate the beacons, is there any way to simulate standard BLE flag or any other way? 
It would be great if you could add a small commit to your library by which we can test the virtual beacons.

**Comment by sbobowiec** [comment]
You can use [nRF Connect App](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) to simulate device (Advertiser tab) with custom advertising data. To simplify whole process of filling data you can clone real device and change specified bytes.
