### ISSUE TITLE
How to use the LimitedMeanRssiCalculator to receive correct values (of rssi) every second?

### ISSUE THREAD

**Issue by frank-vi** [kontaktio/kontakt-android-sdk#177]
I don't understand how to use the LimitedMeanRssiCalculator together with the scanPeriod and/or the deviceUpdateCallbackInterval.
I want to receive, every second, the rssi value ​​of the detected beacons. I want that every rssi to be the result of the arithmetic mean of the last 5 rssi. How should I configure the ProximityManager?

I have configured the proximityManager like this:

`proximityManager.configuration()`
`.scanPeriod(ScanPeriod.RANGING)`
`.scanMode(ScanMode.LOW_LATENCY)`
`.rssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5));`

Should I also set the deviceUpdateCallbackInterval(1000) to receive rssi (calculated with LimitedMeanRssiCalculator) every second? Or i configure activityCheckConfiguration(ActivityCheckConfiguration.create(1000, 500))?

**Comment by frank-vi** [comment]
Setting the inactivityTimeout at 1000ms and the checkPeriod at 500ms in activityCheckConfiguration, it throws me an error because the timeout is less than 3s.
Any suggestions?

**Comment by sbobowiec** [comment]
From our JavaDocs:  The configuration (ActivityCheckConfiguration) consists of 2 parameters - removal inactivityTimeout and checkPeriod.  The former describes time threshold after which beacon device is interpreted as inactive and should be removed. The latter specifies period of search of inactive beacons.

There are some constraints here: inactivity timeout must be no shorter than 3 seconds and check period must be no shorter than 1 second. 

If you want to receive callbacks every second just set second parameter with value >= 1000 and remember that first value must be also greater than 3000. It make no sense to set lower value because in such a case you could receive discover/lost events multiple times even if beacon is nearby phone. To assume if you want to treat beacon as lost one after 3 seconds and get callbacks every second you can use predefined activity check configuration - `ActivityCheckConfiguration.MINIMAL`.
