### ISSUE TITLE
SendBroadcastPermission: action:com.kontakt.sdk.action.BLE_SCAN_ERROR_OCCURRED

### ISSUE THREAD

**Issue by milosgaric23** [kontaktio/kontakt-android-sdk#178]
Hi guys.

I am facing some strange problem.
I have installed new version of library: v4.0.0.
Problem is happening on Huawei P9 Lite device.
This is part of the log:

_.../BluetoothAdapter: getBluetoothLeScanner
.../SendBroadcastPermission: action:com.kontakt.sdk.action.BLE_SCAN_ERROR_OCCURRED, mPermissionType:0
.../BluetoothAdapter: getBluetoothLeScanner_

For some reason, after this error, scanning has stopped, and never again restarted, unless user restarts the bluetooth manually.
Is this maybe some known bug, or device related, hardware related or something like that?

Thanks in advance, if there is something else that I can send in order to fix this problem, be free to "kontakt" me :)

Best regards,
Milos

**Comment by sbobowiec** [comment]
Hey. Does it happens also on other devices? From our experience Huwaei phones aren't so good to work with beacons.

**Comment by robertbielas** [comment]
This can happen from several reasons as I inspect the code:
1. final BluetoothAdapter bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
^ the returned bluetooth adapter  is null (e.g. BT module is unavailable)

2. The bluetooth stack invokes ScanCallback.onScanFailed with the following error codes:
    /**
     * Fails to start scan as BLE scan with the same settings is already started by the app.
     */
    public static final int SCAN_FAILED_ALREADY_STARTED = 1;

    /**
     * Fails to start scan as app cannot be registered.
     */
    public static final int SCAN_FAILED_APPLICATION_REGISTRATION_FAILED = 2;

    /**
     * Fails to start scan due an internal error
     */
    public static final int SCAN_FAILED_INTERNAL_ERROR = 3;

    /**
     * Fails to start power optimized scan as this feature is not supported.
     */
    public static final int SCAN_FAILED_FEATURE_UNSUPPORTED = 4;

    /**
     * Fails to start scan as it is out of hardware resources.
     *
     * @hide
     */
    public static final int SCAN_FAILED_OUT_OF_HARDWARE_RESOURCES = 5;

    /**
     * Fails to start scan as application tries to scan too frequently.
     * @hide
     */
    public static final int SCAN_FAILED_SCANNING_TOO_FREQUENTLY = 6;

I am guessing that since more than 3 years passed, there is no chance to gather some logs? 
Closing the issue, feel free to reopen if the problem occurs again (with potentially more logcat so that we are able to debug the sucker together!).
