### ISSUE TITLE
Build failes with SDK version 4.0.2

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#186]
When setting `com.kontaktio:sdk:4.0.2` in `build.gradle` I get the following error while building with gradle (`com.kontaktio:sdk:4.0.1` however works!):

```
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-kontaktio'.
      > Could not resolve all dependencies for configuration ':react-native-kontaktio:_debugPublishCopy'.
         > Could not find com.kontaktio:sdk:4.0.2.
           Required by:
               KontaktExample:react-native-kontaktio:unspecified
```

**Comment by sbobowiec** [comment]
Did you try to remove gradle cache with following command? 
rm -rf $HOME/.gradle/caches/
Also you can try to invalidate cache in Android Studio (File -> Invalida cache/Restart).

**Comment by robertbielas** [comment]
Closing, because this sdk version is no longer supported - additionally, sdk repository moved from Bintray to Maven Central. 

Now you need to attach the following dependency to the build.gradle script:
implementation 'io.kontakt.mvn:sdk:5.0.xx'

where xx is the newest version of the sdk. (For the most recent version number see here: https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app/build.gradle)
