### ISSUE TITLE
Kontakt.io Android SDK 4.0.3 SecureProfileListener not detecting Smart beacons

### ISSUE THREAD

**Issue by rehmantalha51** [kontaktio/kontakt-android-sdk#198]
Greetings Kontakt.io team, I have been developing apps over a year using kontakt.io sdk, using the latest Android I am unable to get the SecureProfile of my kontakt.io smart beacons whereas the Beacon Pro profile is fetched right away.
(Using iOS sdk it is fetching both smart beacon and beacon pro without any issue)
I have downloaded the latest admin sample app and tried to run with that code as well but only Beacon pro profiles shows up no smart beacon profiles are there.

Any help regarding the issue will be appreciated 

Thanks 
Regards

**Comment by robertbielas** [comment]
@rehmantalha51 Android sdk will not process SmartBeacon's payload into a SecureProfile object because (if we are talking about SB16-2 products) those beacons do not support it. SB16 can only transmit IBeacon / Eddystone frames, which have ScanResponse frames associated with them that broadcast data also present inside SecureProfile frames.

Having said that, in order to receive data from SmartBeacons, you need to register ibeacon / eddystone listeners depending on the configuration of those devices - I would strongly encourage you to inspect sample app's code to see how to do this, or see the documentation here: https://knowledgebase.kontakt.io/mobile/android/qsg/usage/#ibeacon-eddystone-listeners. 

I am closing this issue, but feel free to reopen if you need more details from us.
