### ISSUE TITLE
RunnersL.java line 84 IllegalStateException

### ISSUE THREAD

**Issue by dks0336009** [kontaktio/kontakt-android-sdk#2]
java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:107)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:102)
       at com.kontakt.sdk.android.factory.RunnersL$2.run(RunnersL.java:84)
       at com.kontakt.sdk.android.manager.MonitorController$Consumer.run(MonitorController.java:95)
       at java.lang.Thread.run(Thread.java:818)

BT is enabled.  Exception seems to occur after exiting a region or when powering the device.
Using Nexus 5 running Android 5.1.

**Comment by ghost** [comment]
Hey Kurt, thanks for reporting. Seems that you attempted to launch scanning without turning on BLE.
We've tested the Android SDK including ranging and monitoring against Android 5.1 and there was nothing to fix in the SDK.

I don't know what your connection/scan launch logic is but please remember to handle bluetooth le launch in your code as the SDK does not provide such functionality.

As an example you can download and launch kontakt-beacon-admin-sample-app to see how we organised this logic.

If, however, your problem persists, please send a code snippet demonstrating your approach, thanks.

**Comment by ghost** [comment]
Hey Kurt, have you solved this?

**Comment by edisonspencer** [comment]
Hello @dawid-kontakt I have the same issue described by @dks0336009 

The stacktrace given to me is the following:

```
    java.lang.IllegalStateException: BT Adapter is not turned ON
        at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
        at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:144)
        at com.kontakt.sdk.android.factory.RunnersL$1.run(RunnersL.java:62)
        at com.kontakt.sdk.android.manager.MonitorController$Consumer.run(MonitorController.java:99)
        at java.lang.Thread.run(Thread.java:818)
```

I am trying to implement kontakt.io solution using an Android Service, [described here](http://stackoverflow.com/a/28152838/347119).

At the following line (in the solution present in Stackoverflow):

```
beaconManager.stopMonitoring();
```

I've obtained **"IllegalStateException"**, which I surrounded with a try catch. But once that is done, the exception shown in the stacktrace occurs.

**And all of this happens when I turn off the Bluetooth after started scanning for beacons.**
I am using the latest version of kontakt SDK (**1.0.6**) in **Android Studio**, and with an **ASUS Nexus 7 (Android 5.0.2)**.

Thank you,

**Comment by ghost** [comment]
Does your device perform scan when you turn on the bluetooth again with swallowing the exception?

Scan interruptions are not handled in v1.0.6. This means that before you either start or stop scan you should assume that Bluetooth is turned on. We've already handled this in new version.

However, there is a possibility to detect when the Bluetooth is connecting/connected/disconnecting/disconnected. You can register the `BroadcastReceiver` dynamically with Action `BluetoothAdapter.ACTION_STATE_CHANGED`. There are four states which the `BluetoothAdapter` may be in (`BluetoothAdapter.STATE_CONNECTED`, `BluetoothAdapter.STATE_DISCONNECTED`, `BluetoothAdapter.STATE_CONNECTING`, `BluetoothAdapter.STATE_DISCONNECTING`). 

For the time being  I suggest relying on the states indicated by the `BroadcastReceiver` so that the exception should not occur. I'll implement this approach in [kontakt-beacon-admin-sample-app](https://github.com/kontaktio/kontakt-beacon-admin-sample-app).

New version of the SDK will be released soon.

Thanks

**Comment by edisonspencer** [comment]
Thank you @dawid-kontakt for the tip.
So you mean I should implement the Broadcast Receiver in order to detect Bluetooth changes, and disable the service (scanning) before the exception might occur?
i.e. Disable it on `BluetoothAdapter.STATE_DISCONNECTING` rather than on  `BluetoothAdapter.STATE_DISCONNECTED` in order to still prevent the exception?

**Comment by ghost** [comment]
Exactly. The flow is like the following:

`BluetoothAdapter.STATE_CONNECTING` - create `BeaconManager` instance
`BluetoothAdapter.STATE_CONNECTED` - start scanning
`BluetoothAdapter.STATE_DISCONNECTING` - stop scanning
`BluetoothAdapter.STATE_DISCONNECTED` - disconnect `BeaconManager`

Thanks for reporting btw. If the exception still occurs, please report it, we'll try to figure out how to help you.
