### ISSUE TITLE
BeaconProScanning not working

### ISSUE THREAD

**Issue by sidandroid** [kontaktio/kontakt-android-sdk#222]
Please see logs:

 BeaconProScanActivity: onProfileLost: SecureProfile{macAddress='C1:40:BB:0F:3A:CC', name='TASBeacon', uniqueId='11ai02fQ', firmwareRevision='null', model='ANCHOR_BEACON_2', batteryLevel=99, txPower=-20, rssi=-85, namespace='null', instanceId='null', shuffled=false, telemetry=null, location=KontaktLocation{bleChannel=38, isMoving=false, roomId=120, localTimeMs=384080}, peopleDetectionFrame=null}
 BeaconProScanActivity: onProfileDiscovered: SecureProfile{macAddress='C1:40:BB:0F:3A:CC', name='TASBeacon', uniqueId='11ai02fQ', firmwareRevision='2.6', model='ANCHOR_BEACON_2', batteryLevel=99, txPower=-20, rssi=-91, namespace='null', instanceId='null', shuffled=false, telemetry=null, location=KontaktLocation{bleChannel=38, isMoving=false, roomId=120, localTimeMs=384080}, peopleDetectionFrame=null}
BeaconProScanActivity: onProfilesUpdated: 1
BeaconProScanActivity: onProfileLost: SecureProfile{macAddress='C1:40:BB:0F:3A:CC', name='TASBeacon', uniqueId='11ai02fQ', firmwareRevision='2.6', model='ANCHOR_BEACON_2', batteryLevel=99, txPower=-20, rssi=-89, namespace='null', instanceId='null', shuffled=false, telemetry=null, location=KontaktLocation{bleChannel=38, isMoving=false, roomId=120, localTimeMs=384080}, peopleDetectionFrame=null}
BeaconProScanActivity: onProfileDiscovered: SecureProfile{macAddress='C1:40:BB:0F:3A:CC', name='TASBeacon', uniqueId='11ai02fQ', firmwareRevision='2.6', model='ANCHOR_BEACON_2', batteryLevel=99, txPower=-20, rssi=-95, namespace='null', instanceId='null', shuffled=false, telemetry=null, location=KontaktLocation{bleChannel=38, isMoving=false, roomId=120, localTimeMs=384080}, peopleDetectionFrame=null}
BeaconProScanActivity: onProfileLost: SecureProfile{macAddress='C1:40:BB:0F:3A:CC', name='TASBeacon', uniqueId='11ai02fQ', firmwareRevision='2.6', model='ANCHOR_BEACON_2', batteryLevel=99, txPower=-20, rssi=-95, namespace='null', instanceId='null', shuffled=false, telemetry=null, location=KontaktLocation{bleChannel=38, isMoving=false, roomId=120, localTimeMs=384080}, peopleDetectionFrame=null}
 
Problem is beacon device is fixed position, still it is going on **onProfileLost**..Why??

**Comment by robertbielas** [comment]
@sidandroid I assume those are also your logs, sir, since mac addresses match?
[beacon_pro_logs.txt](https://github.com/kontaktio/kontakt-android-sdk/files/8487106/beacon_pro_logs.txt)

**Comment by robertbielas** [comment]
The reason it happens is because the maximal interval has passed since the last frame broadcasted by your target Beacon Pro had been received by BackgroundScanBroadcastReceiver(*). This interval is also called "inactivity timeout" / "inactivity check": https://developer.kontakt.io/docs/dev-ctr-sdks/ZG9jOjQ3OTM2OTU2-inactivity-check. Note this interval is configurable, so you can adjust it according to your needs (and even disable it altogether by passing ActivityCheckConfiguration.DISABLED when configuring your ProximityManager).  After this interval our target bluetooth peer is considered as "lost" (out of range) if the appropriate scan result has not arrived (and consequently, as stated earlier, has not been received by BackgroundScanBroadcastReceiver).

(*) BackgroundScanBroadcastReceiver is the component of the sdk responsible for receiving scanned payloads from the Bluetooth Stack of your phone.

**Comment by robertbielas** [comment]
Also also, from what I understand, you are using BeaconProScan activity from our samples, correct? Does the result change when you change scanMode from BALANCED to LOW_LATENCY?

**Comment by sidandroid** [comment]
> Also also, from what I understand, you are using BeaconProScan activity from our samples, correct? Does the result change when you change scanMode from BALANCED to LOW_LATENCY?

No result remains the same when you change scanMode from BALANCED to LOW_LATENCY

**Comment by robertbielas** [comment]
@sidandroid
[BleDiagnostitian.zip](https://github.com/kontaktio/kontakt-android-sdk/files/8495797/BleDiagnostitian.zip)
![Screenshot_20220415-134814](https://user-images.githubusercontent.com/56679305/163568967-fc1323e8-de3b-4ed5-97a9-f62cdfbc0d03.png)
A simple app that serves mostly to profile how long it takes to find payloads associated with specific mac addresses by your phone. It does not have any dependency on our sdk. Please share the results how often your phone sees the beacon with the mac address in the logs above.

This app serves to only to provide a diagnostic value. Feel free to play around with it and modify the code to your needs. Most optimally, take your beacon pro to an isolated place and compare how the sample app works compared to this toy (so that the logs / screenshots contain only the desired mac addresses).
