### ISSUE TITLE
Add Battery Level variable in Device class

### ISSUE THREAD

**Issue by XarhsSta** [kontaktio/kontakt-android-sdk#224]
Hello Kontakt team.

We are using the Kontakt SDK to communicate with beacons, and there is a need to display the battery level of a beacon along with its configuration (uniqueId, major, minor, packets it uses etc.) For this we use the Devices API from Kontakt Cloud. We seen from the logs that the battery level of a beacon is shown, but on the [Device class](http://kontaktio.github.io/kontakt-android-sdk/4.0.2/Javadoc/com/kontakt/sdk/android/common/model/Device.html) the battery level isn't available. Is there a way or is it easy to implement this variable in the Device class? This is suggested as an enhancement about the Kontakt SDK.

Thanks for your time!

**Comment by josephkesisoglou** [comment]
Hi Kontakt team, have you had the chance to review this issue? Battery levels are critical for our operation and we are nearing the end-of-life for several hundred beacon batteries deployed across a broad geography, we would appreciate some guidance on this.

Regards, Joseph.

**Comment by robertbielas** [comment]
@XarhsSta @josephkesisoglou 

Device class is the Kio Cloud model. 
~~What you saw in your logcat (the battery level) came from the BLE scan.~~

The battery by default is still uploaded whenever you run sdk scan (if you did not invoke monitoringEnabled(false) on your ProximityManager) and the phone received payloads containing the battery in the telemetry / other frames.  

If you want to receive the battery status of a particular beacon, you can use Kio AppsApi (right now, sdk does not include the http client for this backend). A sample request:
`curl --location --request GET 'https://apps.cloud.us.kontakt.io/v3/telemetry?trackingId=<lower-case-mac-of-beacon>&endTime=<UTC-END-TIME>&startTime=<UTC-START-TIME>&sort=timestamp' \
    --header 'Api-Key: <API-Key, same what you pass to the SDK.init()>' \
    --header 'Content-Type: application/json'`
    
^ Look for the responses containing the battery levels. UTC-END-TIME / UTC-START-TIME are formatted in the following way: yyyy-mm-ddThh:MM:SSZ , e.g. 2022-02-14T13:21:21Z     

If you want to filter the results by the sending phone, instead of trackingId, use sourceId parameter. In case of Android phones, it will be the AndroidId of your application, which you can fetch by using the following snippet:
`String sourceId = Settings.Secure.getString(context.getContentResolver(),
            Settings.Secure.ANDROID_ID);`
            
AppsApi Documentation: https://developer.kontakt.io/docs/dev-ctr-loc-occ-api/d970c7e7d702b-retrieve-telemetry-by-tracking-id
    
    
Edit: Now to answer your question - ~~we do not plan to add this property to the Device, as the Device class is more like a Retrofit model, not BLE scan model (two separate use cases).~~      

Edit 2: Actually, there is a battery field in the Device model received from api! Ok, let's see what can be done about it.

**Comment by robertbielas** [comment]
Battery exposed as a Device property in sdk 7.0.10.
