### ISSUE TITLE
the sdk crashed on Android 14

### ISSUE THREAD

**Issue by mahmoud-elsadany** [kontaktio/kontakt-android-sdk#233]
java.lang.SecurityException:
 One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by andreas-umbricht-swiss-dev** [comment]
I receive the same error.
This should be marked as very, very urgent since Android 14 is already available for a couple of months.
And additionally it would be very easy to solve:

ProximityManagerImpl.java line 187:
`context.registerReceiver(bleScanErrorOccurredReceiver, intentFilter);`
to
`context.registerReceiver(bleScanErrorOccurredReceiver, intentFilter, Context.RECEIVER_EXPORTED);`

Thanks in advance

**Comment by andreas-umbricht-swiss-dev** [comment]
Thanks for acknowledging this issue @mahmoud-elsadany.
Do you have any timeline when a new version will be available?
