### ISSUE TITLE
Unable to update Smart Beacons to firmware v3.0

### ISSUE THREAD

**Issue by rishi-ios** [kontaktio/kontakt-android-sdk#35]
Hi,

We are using Smart Beacons for one of our projects both in iOS and Android platform.

Recently on logging in Kontakt web panel, under devices section there is a green info button showing an v3.0 firmware update available for all smart beacons.

Currently our beacons have  Firmware Revision - 2.6 and  Hardware Revision - 2.2

We are following this link to update smart beacons 

https://support.kontakt.io/hc/en-gb/articles/201508431-How-to-check-and-upgrade-your-Smart-Beacon-firmware

On iPAD app after entering Admin Mode it is showing no update available and "Update" button on top right is disabled. 

We have make sure that we are in close range of beacons and we are able to see list of beacons successfully but update button is disabled and there is no update icon appearing  in the list.

Please let us know how to update the smart beacons to latest firmware and also is there any other way to update the beacon firmware ?

Thanks

**Comment by dawidgdanski** [comment]
Hey @rishi-ios. The firmware upgrade is not supported by Android platform at the moment. The only way to make it done is to use iOS Administrative Application. However, as far as I know the functionality is temporarily switched off because of some improvements that have been already done. I spoke with iOS engineers and the application is about to be released. In few days the functionality will be available again. Apologies for temporary inconvenience.

**Comment by rishi-ios** [comment]
Thanks for the reply. Please let me know how will I come to know that this functionality is available now.
I mean will  "Update" button began working automatically inside current app after sometime or  will there be an App Store update of the iOS app  ?

**Comment by jakubkontakt** [comment]
Closing as this is working in iOS app available on AppStore
