### ISSUE TITLE
Ranging/monitoring results are inconsistent after upgrade to 2.00 and Eddystone

### ISSUE THREAD

**Issue by mw-cosmose** [kontaktio/kontakt-android-sdk#36]
Hi,

I've been using the previous version of android sdk for ibeacons without any problems. Recently I've decided to give eddystone a try and updated my beacons as well as the sdk. The results of scanning are now very inconsistent even though the android device and beacons are right next to each other. For some scans I only get onScanStart and onScanStop called and no onEvent. Other times I'm seeing only SPACE_ENTERED events. From time to time BLE devices are found and DEVICE_DISCOVERED is emitted but no DEVICES_UPDATE. Another strange behaviour is ranging (active period = 5000, passive period = 0) is going on forever and never calls onScanStop.
To see if my configuration is at fault here I downloaded and started the kontakt-beacon-admin-sample-app. The results are unfortunately similarly strange. When using eddystone monitoring a list of some (about 2 out of 5) beacons appears after a few minutes and then quickly disappears. Sometimes beacon data is clearly wrong (temperature, distance and power is 0.0) which may point to hardware problems. I will try reverting to ibeacon later to see if it makes any difference.

My scan configuration is:
new ScanContext.Builder()
      .setEddystoneScanContext(EddystoneScanContext.DEFAULT)
      .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
      .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
      .setScanPeriod(new ScanPeriod(5000, 10000))
      .build()
And my device is Moto G with Android 5.0.2.

Any advice on what could be causing the issues?

Thanks

**Comment by dawidgdanski** [comment]
Hey @mw-cosmose. The problem with scan may have different backgrounds. We've tested scan performance on many devices and results vary depending on the device's manufacturer. We experienced similar situation with poor performance on our Moto G (2nd generation 2014). In comparison, we received the scan results faster and more frequently on Samsung and LG devices.  

`Another strange behaviour is ranging (active period = 5000, passive period = 0) is going on forever and never calls onScanStop.`

Strange thing,  we have this situation tested but I'm including the issue on that to our backlog. 

`Sometimes beacon data is clearly wrong (temperature, distance and power is 0.0) which may point to hardware problems.`

Well, the temperature in Eddystone device comes with TLM advertisting packet so sometimes you simply may receive default value (0) if the Android device has not received yet the TLM frame.

You can control which frame types are required to be scanned [before first notification of the Eddystone device presence](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/configuration/scan/EddystoneScanContext.Builder.html#setTriggerFrameTypes-java.util.Collection-).

`My scan configuration is:`
`new ScanContext.Builder()`

`...`

`.setScanPeriod(new ScanPeriod(5000, 10000))`
`.build()`

So you want the Android device to scan for 5 s and remain idle for 10s. Notice please, that by default [the DEFAULT ActivityCheckConfiguration is enabled](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/configuration/ActivityCheckConfiguration.html). The android device performs periodic check in search of Bluetooth devices that have become inactive (the Android devices has stopped receiving signal from them).

I suggest manipulating ScanContext's parameters to see how scan depends on them and reading what the documentation states about them. Think, this will clarify some doubts. 

I'm leaving the issue open because of the issue with stopping ranging.

I'll let you know once I find out anything valuable.

**Comment by mw-cosmose** [comment]
Hi,

I've tested my application on Samsung GS3 and can confirm that scanning is working as expected and ranging stops correctly. It seems the problem is indeed with the moto g. To confirm this I tried eddystone SDK from other vendor and they had the exact same problem. I managed to solve the issue for now by using monitoring and detaching/disconnecting scan in onScanStop. Also increasing scan period to 10s gives moto g enough time to yield better results. I would still like to know if ranging is fixed on moto g so please keep me in the loop :)

Thanks!

**Comment by dawidgdanski** [comment]
Hey @mw-cosmose 

Glad to hear, glad to hear:)

**Comment by jakubkontakt** [comment]
Hi @mw-cosmose  
Could you update to version 2.0.1 and tell us is your problem still exists?
