### ISSUE TITLE
Duplicate files error

### ISSUE THREAD

**Issue by chawlatarika5** [kontaktio/kontakt-android-sdk#38]
I tried both the ways mentioned in the tutorial on this link: http://docs.kontakt.io/android-sdk/2.0.0/quickstart/#latest-version. I also tried integrating the SDK libraries manually from here: https://github.com/kontaktio/Android-SDK/. I also tried this solution mentioned in link: http://stackoverflow.com/questions/20827885/android-studio-0-4-duplicate-files-copied-in-apk-meta-inf-license-txt

Here is the error I am getting:

---

Error:Execution failed for task ':app:packageDebug'.

> Duplicate files copied in APK main/AndroidManifest.xml

File 1: /Users/tarikachawla/AndroidStudioProjects/vault-app/SecureVault-Android/app/build/intermediates/exploded-aar/com.kontakt.sdk.android/kontakt.io-api-client/2.0.0/jars/classes.jar

File 2: /Users/tarikachawla/AndroidStudioProjects/vault-app/SecureVault-Android/app/build/intermediates/exploded-aar/com.kontakt.sdk.android/kontakt.io-common-sdk/2.0.0/jars/classes.jar

I would really appreciate your help.

**Comment by Dadoffak** [comment]
I had the very same problem and solved it by removing the manifest File from two of the jar files. (Deflate the jar file, remove the manifest and use the standard java jar tool to rebuild it) 

I really don't know how such a bug is possible in a release, but maybe this only happens when using Eclipse and nobody tested this way of building an application.

**Comment by jhewt** [comment]
@Dadoffak It's the same using Android Studio.

**Comment by chawlatarika5** [comment]
Thank you so much for the help. I tried this, but for some reason it did not work for me. I solved it by excluding 'main/AndroidManifest.xml'. I added the following code in build.gradle (Module:app):
android {
packagingOptions {
        exclude 'main/AndroidManifest.xml'
    }
}

**Comment by Dadoffak** [comment]
I don't use Android Studio, but as it seems you have to do it like I wrote:

1) Extract jar
2) Physically remove Manifest
3) Rebuild jar using standard java jar console tool

After doing this check, if the structure of the old jar is the same in the new jar (you might need some tries, if you're not used to using jar)

Hope this will help

**Comment by jakubkontakt** [comment]
Next release will have fixed all jars and only single jar will be needed.

**Comment by pendragonformsrepo** [comment]
I have the same problem, and his solution does not work for me.
'Installation failed with message INSTALL_PARSE_FAILED_MANIFEST_MALFORMED.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?'

And it fails

**Comment by jakubkontakt** [comment]
@pendragonformsrepo 
Are you sure that Jar did not have AndroidManifest.xml file?

Please post more details about your configuration, because your message seems pretty bad and should never appear.
