### ISSUE TITLE
How to do Indoor Navigation Using Beacon.

### ISSUE THREAD

**Issue by gkakkar** [kontaktio/kontakt-android-sdk#52]
We want to create an application for indoor navigation using Kontakt beacons. Does Kontakt beacon provides SDK to develop the application for indoor direction finding.
I have found that Estimote beacons team has released the sdk for indoor navigation for IOS http://estimote.com/indoor/
but We want to develop application for Android.Can you guide us how to proceed.

**Comment by jakubkontakt** [comment]
We do not provide that kind of solutions. An indoor positioning system is a very complex piece of software and we could make simple SDK for demo purposes, like some of our competitors do, that would work in a single room, but wouldn't really scale for full-fledged deployments, so ultimately would we a waste of our resources, because it wouldn't be really useful for our clients in the real world.

Instead of that we're focusing on providing the best possible platform for our partners to build solutions like that. If you need a professional beacon-based indoor navigation system we recommend contacting one of our partners specialising in systems like that. Please get in touch with [indoo.rs](http://indoo.rs/), [Nextome](http://www.nextome.org/) or [Pointr](http://www.pointrlabs.com/) (to name just a few of them) to learn more about what's possible.
