### ISSUE TITLE
Grabbing Major and Minor Values in ProximityListener

### ISSUE THREAD

**Issue by Jacob-Terrado** [kontaktio/kontakt-android-sdk#72]
I'm currently tracking my beacons based on their Proximity UUIDs/ IBeaconRegions. Since my application needs to use multiple beacons and multiple UUID's, I had to resort to using the following `IBeaconFilter` to detect the beacons in the onEvent method (what is suggested in a couple of the issues posted on Github).

``` java
private IBeaconFilter filter() {
    @Override
    public boolean apply(IBeaconAdvertisingPacket packet) {
        return iBeaconSpaceUUIDHashMap.contains(packet.getProximityUUID());
    }
};
```

While this method properly fires off the `SPACE_ENTERED` event for a given UUID, I am unable to parse the Major and Minor values (and therefore am not able to distinguish between Beacons with the same UUID and different Major/ Minor values). Is it possible to grab the Major and Minor values as if I was filtering the Beacons using `.setIBeaconRegions({...})` in my `IBeaconScanContext`?

**Comment by jakubkontakt** [comment]
Hi @Jacob-Terrado 
Do you mean that when `onEvent()` is called all beacons has the same Major/minor values? Even when they have different unique ids?

**Comment by Jacob-Terrado** [comment]
Hi @jakubkontakt ,
When `onEvent()` fires from my ProximityListener, the following code:

``` java
public void onEvent(BluetoothDeviceEvent event) {
    IBeaconDeviceEvent dEvent = (IBeaconDeviceEvent) event;
    IBeaconRegion region = dEvent.getRegion();

    switch(event.getType()) {
        case SPACE_ABANDONED:
            Log.i(TAG, "SPACE_ABANDONED");
            break;
        case SPACE_ENTERED:
            Log.i(TAG, "SPACE_ENTERED; major: " + region.getMajor() + " minor: " + region.getMinor());
            break;
    }
}
```

prints out "SPACE_ENTERED; major: 0 minor: 0.

The event SPACE_ENTERED is only called once even though there are multiple IBeacons being detected (as seen by my log messages in the filter) that satisfy the proximityUUID requirement. I am only able to pull the major and minor values of the IBeacons in the IBeaconFilter, and not in the onEvent method.

**Comment by jakubkontakt** [comment]
Hi @Jacob-Terrado Could you post your scan context configuration?

**Comment by Jacob-Terrado** [comment]
``` java
  private IBeaconScanContext iBeaconScanContext =
      new IBeaconScanContext.Builder()
          .setEventTypes(eventTypeList)
          .setIBeaconFilters(Collections.singletonList(filter))
          .build();

  private ScanContext scanContext =
      new ScanContext.Builder()
          .setIBeaconScanContext(iBeaconScanContext)
          .setScanMode(SCAN_MODE)
          .setScanPeriod(new ScanPeriod(ACTIVE_PERIOD, PASSIVE_PERIOD))
          .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
          .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
          .build();
```

**Comment by jakubkontakt** [comment]
OK, it seems that you mixed two concepts: Regions and Filtering

When you created such ScanContext you did not set any region to IBeaconScanContext so default one was created to you, with following values:

Proximity: f7826da6-4fa2-4e98-8024-bc5b71e0893e
Major: 0
Minor: 0

This Region actually did not check any of this values and all scanned beacons are passing through. And all of them are belonging to this region, so following code:

> ```
>  case SPACE_ENTERED:
>         Log.i(TAG, "SPACE_ENTERED; major: " + region.getMajor() + " minor: " + region.getMinor());
>         break;
> ```

will always result in printing 

> "SPACE_ENTERED; major: 0 minor: 0.

Filtering gives you possibility to filter beacons after they are assigned to one of the regions.  In your scenario all of beacons were assigned to default region and after that only this beacons which fulfil your filter will be returned in `onEvent()`

> ```
> private IBeaconFilter filter() {
>     @Override
>     public boolean apply(IBeaconAdvertisingPacket packet) {
>         return iBeaconSpaceUUIDHashMap.contains(packet.getProximityUUID());
>     }
> };
> ```

<b>But they are still assigned to default region with above values!</b>

So instead of checking Major(M) and minor(m) from region you should could following:
1. Define more regions (max 20)
2. Get Major and minor from device(s)

Please note also, that event `SPACE_ENTERED` will be raised only once for first discovered device, since all of them in your configuration belongs to the same one.

**Comment by Jacob-Terrado** [comment]
Thank you for clearing that up. 

As a follow up, if I would need to:
1. Detect `IBeaconRegions` of multiple beacons (more than 20--no more than 20 different UUIDs, but multiple combinations of Majors and minors per UUID)
2. Grab the ProximityUUID, Major, and Minor values in the `SPACE_ENTERED` case in `onEvent()`

would defining IBeaconRegions of different UUIDs without the Major and minor and setting the above filter work?

**Comment by jakubkontakt** [comment]
Unfortunately current implementation will check in that case exact values so all three values are needed. 

But soon we are going to release next version of sdk, and that version will allow you to do it

**Comment by Jacob-Terrado** [comment]
Thank you for letting me know!

**Comment by Jacob-Terrado** [comment]
Do you by any chance have an estimated time of completion for the next version of the SDK?

**Comment by jakubkontakt** [comment]
We have release 2.1.0 version of our SDK, and this feature is now implemented. Please try it!

**Comment by Jacob-Terrado** [comment]
Hi @jakubkontakt ,

Thank you for the update. I was looking into the implementation of this and currently have the following code:

``` java
  private IBeaconScanContext iBeaconScanContext =
      new IBeaconScanContext.Builder()
          .setIBeaconFilters(beaconFilters)
          .setEventTypes(eventTypeList)
          .build();

  private ScanContext scanContext =
      new ScanContext.Builder()
          .setIBeaconScanContext(iBeaconScanContext)
          .setScanMode(SCAN_MODE)
          .setScanPeriod(new ScanPeriod(ACTIVE_PERIOD, PASSIVE_PERIOD))
          .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
          .setActivityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
          .build();
```

``` java
public void onEvent(BluetoothDeviceEvent event) {
    IBeaconDeviceEvent dEvent = (IBeaconDeviceEvent) event;
    IBeaconRegion region = dEvent.getRegion();

    switch(event.getType()) {
        case SPACE_ABANDONED:
            Log.i(TAG, "SPACE_ABANDONED");
            break;
        case SPACE_ENTERED:
            Log.i(TAG, "SPACE_ENTERED; UUID: " + region.getProximity() + " major: " + region.getMajor() + " minor: " + region.getMinor());
            break;
    }
}
```

I am not specifying the IBeaconRegions, but would still get the following printed out in  `onEvent()`:
SPACE_ENTERED; UUID: f7826da6-4fa2-4e98-8024-bc5b71e0893e major: -1 minor: -1

When I do attempt to specify, the IBeaconRegions, I only change the `getProximity()` method to return the appropriate UUID

``` java
IBeaconRegion region = new IBeaconRegion() {

    @Override
     public UUID getProximity() {
        return UUID.fromString("Region UUID");
    }
    /**
     * Other Methods here
     */
};
```

It appears that by specifying the IBeaconRegion like above, the IBeacons are not being detected as their Major (M) and minor (m) are not matching (they default to 0).

How would I go about defining an IBeaconRegion with only the UUID?

Thanks

**Comment by jakubkontakt** [comment]
HI @Jacob-Terrado 

Proper way is to build region in following way:

```
BeaconRegion region = new BeaconRegion.Builder()
        .setProximity(UUID.fromString("6565d504-e306-4119-8266-0f8d4401cd0a"))
        .setMajor(BeaconRegion.ANY_MAJOR) //any major, default value
        .setMinor(BeaconRegion.ANY_MINOR) //any minor, default value
        .build();
```

**Comment by Jacob-Terrado** [comment]
Hi @jakubkontakt,
    I copied the following code, but is unfortunately still unable to grab the IBeaconRegion's Major (M) and Minor (m) values--it gives me the default -1 values. 

If my IBeacon has the following information: UUID (f7826da6-4fa2-4e98-8024-bc5b71e0893e), Major (1000), and Minor (4645), is there a way for me to parse the Major and Minor values with the above approach?

Or perhaps, if I define IBeaconRegions for each of my UUIDs, would the event `DEVICE_DISCOVERED` be fired more frequently?

**Comment by jakubkontakt** [comment]
Hi @Jacob-Terrado 

```
public void onEvent(BluetoothDeviceEvent event) {
    IBeaconDeviceEvent dEvent = (IBeaconDeviceEvent) event;
    IBeaconRegion region = dEvent.getRegion();

    switch(event.getType()) {
        case SPACE_ABANDONED:
            Log.i(TAG, "SPACE_ABANDONED");
            break;
        case SPACE_ENTERED:
            Log.i(TAG, "SPACE_ENTERED; UUID: " + region.getProximity() + " major: " + region.getMajor() + " minor: " + region.getMinor());
            break;
    }
}
```

Actually your snippet is grabing proper values. Since you have not set major and minor we can't deduce that for you. That means that if any beacon has the same UUID as your region, will be put into this region.

Let me show the example of that:

Region definition:

```
UUID: f7826da6-4fa2-4e98-8024-bc5b71e0893e
Major/minot not specified.
```

Let's assume we have 2 beacons:

```
UUID: f7826da6-4fa2-4e98-8024-bc5b71e0893e
Major: 1
Minor: 10
```

and 

```
UUID: f7826da6-4fa2-4e98-8024-bc5b71e0893e
Major: 2
Minor: 20 
```

As a result both of them will be assigned to the same region, but region have major/minor with default values -1. (Since we didn't set any values)

When first of them is scanned SPACE_ENTERED is also called, but for second one is not. For both of them DEVICE_DISCOVERED is called only once as long as their are in range.

This result as well that if you have beacons with different Proximity you need to set region for each of them.

With the latest update you do not have to set major/minor for region, so there is more flexibility with setting them up.

I am still trying understand what do you want to achieve and what are the expected results.
