### ISSUE TITLE
No ScanPeriod set means endless?

### ISSUE THREAD

**Issue by robachmann** [kontaktio/kontakt-android-sdk#94]
What happens if I don't set a `ScanPeriod` in `ScanContext.Builder()` in version 2.1.1? Will the scanner work until I call `proximityManager.finishScan()`? That's would be what I'm looking for (analogous to Apple's Core Location Framework). 

Are there any tips how battery drain of the smartphone can be reduced in such an "endless scan mode"? Basically I know which UUIDs I'm interested in but I need to get notifications when I enter a certain area withing a few seconds.

**Comment by michaldrabik** [comment]
The default `ScanPeriod` is `ScanPeriod.RANGING` which actually means constant scanning without breaks. If you care about battery drain, and entering certain areas then maybe periodical Monitoring is what you are looking for (instead of constant Ranging). More info about Monitoring and Spaces here: 
http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#basic-usage-space-selection

**Comment by robachmann** [comment]
Wonderful thank you
